version: '2'
services:
  redis:
    image: redis:3.0.7

  bot:
    build: .
    restart: always
    ports:
      - 80:4000
      - 443:4000
      - 4000:4000
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=4000
      - REDIS__HOST=redis
      - REDIS__PORT=6379
      - URL
      - TELEGRAM__TOKEN
      - GOOGLE__MAPS__KEY
